description: alignment handbook trials

target:  
  service: sing  
  name: aims-sing-east-us2 #GenAI-Shared-CanadaCtr #aims-sing-east-us2  
  workspace_name: aims-sing-res-eu-WS

environment:
  image: amlt-sing/acpt-pytorch-2.0.1-py3.10-cuda11.8
  setup:
    - nvcc --version
    - pip list
    - pip install torch==2.1.2
    - pip install .
    - pip install deepspeed==0.12.6
    - pip install flash-attn==2.3.6 --no-build-isolation
    - pip install mlflow azureml-mlflow
 
code:
  local_dir: $CONFIG_DIR/

storage:
  posttraining:
    storage_account_name: customdataws9388857230
    container_name: post-training
    mount_dir: /mnt/posttraining
  aimsllmeus2users:
    storage_account_name: aimsllmeus2
    container_name: users
    mount_dir: /mnt/aimsllmeus2users

jobs:
- name: dpo_issue_1078_mixtral8x7_prm
  sla_tier: premium  # Default: premium
  execution_mode: basic  # Default: basic
  sku: 4xG8-H100-IB
  priority: high
  process_count_per_node: 1
  command:
    - echo "check filesystem space"
    - df -h
    - echo "check pwd"
    - pwd
    - ls -lh
    - nvcc --version
    - pip list

    - ACCELERATE_LOG_LEVEL=info accelerate launch 
      --num_processes 32 
      --num_machines 4 
      --main_process_ip $${MASTER_ADDR} 
      --main_process_port $${MASTER_PORT}  
      --machine_rank $${NODE_RANK} 
      --config_file recipes/accelerate_configs/deepspeed_zero3.yaml
      scripts/run_dpo.py recipes/mixtral8x7/dpo/config_full.yaml
  submit_args:
    max_run_duration_seconds: 1209600   # 14 days
    env:
      { AMLT_DOCKERFILE_TEMPLATE: DEFAULT }
- name: dpo_issue_1078_mixtral8x7_stf
  sla_tier: standard  # Default: premium
  execution_mode: basic  # Default: basic
  sku: 4xG8-H100-IB
  priority: high
  process_count_per_node: 1
  command:
    - echo "check filesystem space"
    - df -h
    - echo "check pwd"
    - pwd
    - ls -lh
    - nvcc --version
    - pip list

    - ACCELERATE_LOG_LEVEL=info accelerate launch 
      --num_processes 32 
      --num_machines 4 
      --main_process_ip $${MASTER_ADDR} 
      --main_process_port $${MASTER_PORT}  
      --machine_rank $${NODE_RANK} 
      --config_file recipes/accelerate_configs/deepspeed_zero3.yaml 
      scripts/run_dpo.py recipes/mixtral8x7/dpo/config_full.yaml
  submit_args:
    max_run_duration_seconds: 1209600   # 14 days
    env:
      { AMLT_DOCKERFILE_TEMPLATE: DEFAULT }