description: alignment handbook trials

target:  
  service: sing  
  name: aims-sing-east-us2 #GenAI-Shared-CanadaCtr #aims-sing-east-us2  
  workspace_name: aims-sing-res-eu-WS

environment:
  image: customized_nvcr:nvidia24.03-ds0.14.1.b-fa2.5.6-te1.6.0.beta2-mb0.5.1.b2-gg.b-20240331
  username: structureddl
  registry: structureddl.azurecr.io
  setup:
    - nvcc --version
    - pip list
    - pip install .
    - pip install azureml-sdk
    - pip list
 
code:
  local_dir: $CONFIG_DIR/

storage:
  posttraining:
    storage_account_name: customdataws9388857230
    container_name: post-training
    mount_dir: /mnt/posttraining
  aimsllmeus2users:
    storage_account_name: aimsllmeus2
    container_name: users
    mount_dir: /mnt/aimsllmeus2users
  phyagimodelsdev:
    storage_account_name: phyagimodels
    container_name: development
    mount_dir: /mnt/phyagimodelsdev
  outputeus:
    storage_account_name: genaiposttrain4251659764
    container_name: azureml-blobstore-eefac177-8860-4468-a116-720fdebd3ec0 
    mount_dir: /mnt/outputeus
  outputweu:
    storage_account_name: genaiposttrain8338951232
    container_name: azureml-blobstore-b14553a2-8092-4dcc-8be4-5ac660ae22c5 
    mount_dir: /mnt/outputweu
  outputuks:
    storage_account_name: genaiposttrain4725474871
    container_name: azureml-blobstore-4a91e26d-0502-4b1b-a77b-aa6c72cc88ca 
    mount_dir: /mnt/outputuks
  outputgenaiws:
    storage_account_name: singularitygen5747793554
    container_name: azureml-blobstore-0f1f31b1-e859-48c9-bae5-6106db02cec5 
    mount_dir: /mnt/outputgenaiws
  outputsingreseu:
    storage_account_name: aimssingreseuw7843007229
    container_name: azureml-blobstore-a7dd4d8a-fecc-4027-84dc-c0db39a570cb
    mount_dir: /mnt/outputsingreseu
  outputsingcac:
    storage_account_name: genaiposttrain3546844484
    container_name: azureml-blobstore-040d9d76-189c-4eaa-a0c6-fab4f045414b
    mount_dir: /mnt/outputsingcac
  tsinterns:
    storage_account_name: tsinterns
    container_name: agoswami
    mount_dir: /mnt/tsinterns


jobs:
- name: dpo_issue_1078_phi_moe_prm
  sla_tier: premium  # Default: premium
  execution_mode: basic  # Default: basic
  sku: 4xG8-H100-IB
  priority: high
  process_count_per_node: 1
  command:
    - echo "check filesystem space"
    - df -h
    - echo "check pwd"
    - pwd
    - ls -lh
    - nvcc --version
    - pip list

    - ACCELERATE_LOG_LEVEL=info accelerate launch 
      --num_processes 32 
      --num_machines 4 
      --main_process_ip $${MASTER_ADDR} 
      --main_process_port $${MASTER_PORT}  
      --machine_rank $${NODE_RANK} 
      --config_file recipes/accelerate_configs/deepspeed_zero3.yaml
      scripts/run_dpo.py recipes/mixtral8x7/dpo/config_full_phi_moe.yaml
  submit_args:
    max_run_duration_seconds: 1209600   # 14 days
    env:
      { AMLT_DOCKERFILE_TEMPLATE: DEFAULT }
- name: dpo_issue_1078_phi_moe_std
  sla_tier: standard  # Default: premium
  execution_mode: basic  # Default: basic
  sku: 4xG8-H100-IB
  priority: high
  process_count_per_node: 1
  command:
    - echo "check filesystem space"
    - df -h
    - echo "check pwd"
    - pwd
    - ls -lh
    - nvcc --version
    - pip list

    - ACCELERATE_LOG_LEVEL=info accelerate launch 
      --num_processes 32 
      --num_machines 4 
      --main_process_ip $${MASTER_ADDR} 
      --main_process_port $${MASTER_PORT}  
      --machine_rank $${NODE_RANK} 
      --config_file recipes/accelerate_configs/deepspeed_zero3.yaml 
      scripts/run_dpo.py recipes/mixtral8x7/dpo/config_full_phi_moe.yaml
  submit_args:
    max_run_duration_seconds: 1209600   # 14 days
    env:
      { AMLT_DOCKERFILE_TEMPLATE: DEFAULT }