# Model arguments
model_name_or_path: tlg7b_output_dir
torch_dtype: null
trust_remote_code: true

# Data training arguments
# For definitions, see: src/h4/training/config.py
# chat_template: "{% for message in messages %}{{'<|' + message['role'] + '|>' + '\n' + message['content'] + '<|end|>\n' }}{% endfor %}{{ eos_token }}"

dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 0.1
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: dontcare
learning_rate: 5.0e-7
log_level: info
logging_steps: 1
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: data/dontcare
per_device_train_batch_size: 1
per_device_eval_batch_size: 4
push_to_hub: true
save_strategy: "no"
seed: 42
warmup_ratio: 0.1