# Model arguments
model_name_or_path: phi3_noacad_v0improved_5_3_8b_phase2_20240326_rc0_0
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true
trust_remote_code: true

chat_template: "{% for message in messages %}{{'<|' + message['role'] + '|>' + '\n' + message['content'] + '<|end|>\n' }}{% endfor %}{{ eos_token }}"
dataset_mixer:
  HuggingFaceH4/deita-10k-v0-sft: 1.0

dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 12
dataloader_num_workers: 12
lazy_preprocess: true
mask_user_and_system_tokens: true
packing: false
system_start_token: <|system|>
system_end_token: <|end|>
user_start_token: <|user|>
user_end_token: <|end|>

# SFT trainer config
bf16: true
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
#hub_model_id: zephyr-7b-sft-full
#hub_strategy: every_save
learning_rate: 5.0e-06
#2.0e-05
log_level: info
logging_steps: 2  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: 16
num_train_epochs: 1
output_dir: data/phi-3b-sft-pipeline-new
overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 24
# don't push when running on aml
# push_to_hub: true
remove_unused_columns: true
report_to:
- tensorboard
# 2/25: save_strategy is working now, can turn on.
save_strategy: "no"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1